# Generated by Django 5.0.7 on 2024-08-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
