# Generated by Django 5.0.7 on 2024-08-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
