# Generated by Django 5.0.7 on 2024-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_color_size_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='pid',
            field=models.IntegerField(default=1),
        ),
    ]
