# Generated by Django 5.0.7 on 2024-09-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_images_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pid',
            field=models.IntegerField(),
        ),
    ]
