# Generated by Django 5.0.7 on 2024-09-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_rename_pincode_order_pin_code_alter_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
