# Generated by Django 5.0.7 on 2024-09-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
