# Generated by Django 5.0.7 on 2024-09-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
