# Generated by Django 5.0.7 on 2024-09-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
