# Generated by Django 5.0.7 on 2024-09-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_orderitem_is_canceled_orderitem_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_returned',
        ),
    ]
