# Generated by Django 5.0.7 on 2024-11-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
