# Generated by Django 5.0.7 on 2024-11-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
