# Generated by Django 5.0.7 on 2024-11-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
