# Generated by Django 5.0.7 on 2024-11-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
