# Generated by Django 5.0.7 on 2024-12-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='image_id',
        ),
    ]
