# Generated by Django 5.0.7 on 2024-12-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_remove_variants_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='pid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
