# Generated by Django 5.0.7 on 2024-12-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_variants_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='pid',
            new_name='image_id',
        ),
    ]
