# Generated by Django 5.0.7 on 2024-12-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_rename_pid_variants_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='image_id',
        ),
    ]
