# Generated by Django 5.0.7 on 2025-10-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_variants_is_available_alter_variants_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='variants',
            unique_together={('product', 'color', 'size')},
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'color', 'size'], name='store_varia_product_0caf72_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'is_available'], name='store_varia_product_d270d9_idx'),
        ),
    ]
