# Generated by Django 5.0.7 on 2025-10-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_variants_size_alter_variants_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, help_text='Small thumbnail used as the color swatch on PDP', null=True, upload_to='color_thumbs/'),
        ),
    ]
