# Generated by Django 5.0.7 on 2025-10-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pid',
            field=models.IntegerField(help_text='Stores Color.id for color-specific images'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=3),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product', 'pid'], name='store_image_product_01d559_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'color', 'is_available'], name='store_varia_product_fc9351_idx'),
        ),
    ]
