# Generated by Django 5.0.7 on 2025-10-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_alter_images_pid_alter_variants_size_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='images',
            name='store_image_product_01d559_idx',
        ),
        migrations.RemoveIndex(
            model_name='variants',
            name='store_varia_product_0caf72_idx',
        ),
        migrations.RemoveIndex(
            model_name='variants',
            name='store_varia_product_fc9351_idx',
        ),
        migrations.RemoveField(
            model_name='images',
            name='pid',
        ),
        migrations.AlterUniqueTogether(
            name='variants',
            unique_together={('product', 'size')},
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size')], default='None', max_length=10),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'size'], name='store_varia_product_6767f7_idx'),
        ),
        migrations.RemoveField(
            model_name='variants',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
