# Generated by Django 5.0.7 on 2025-10-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_cart_size_cart_variant_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='uniq_user_product_variant_size',
        ),
    ]
