# Generated by Django 5.0.7 on 2025-10-17 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_remove_cart_uniq_user_product_variant_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'variant', 'size'), name='uniq_user_product_variant_size'),
        ),
    ]
