# Generated by Django 6.0.3 on 2026-03-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
