# Generated by Django 5.0.7 on 2024-08-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
